/*
openapi for sibyl2 server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ObjectWorkspaceConfig struct for ObjectWorkspaceConfig
type ObjectWorkspaceConfig struct {
	RepoId  *string `json:"repoId,omitempty"`
	RevHash *string `json:"revHash,omitempty"`
}

// NewObjectWorkspaceConfig instantiates a new ObjectWorkspaceConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectWorkspaceConfig() *ObjectWorkspaceConfig {
	this := ObjectWorkspaceConfig{}
	return &this
}

// NewObjectWorkspaceConfigWithDefaults instantiates a new ObjectWorkspaceConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectWorkspaceConfigWithDefaults() *ObjectWorkspaceConfig {
	this := ObjectWorkspaceConfig{}
	return &this
}

// GetRepoId returns the RepoId field value if set, zero value otherwise.
func (o *ObjectWorkspaceConfig) GetRepoId() string {
	if o == nil || isNil(o.RepoId) {
		var ret string
		return ret
	}
	return *o.RepoId
}

// GetRepoIdOk returns a tuple with the RepoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectWorkspaceConfig) GetRepoIdOk() (*string, bool) {
	if o == nil || isNil(o.RepoId) {
		return nil, false
	}
	return o.RepoId, true
}

// HasRepoId returns a boolean if a field has been set.
func (o *ObjectWorkspaceConfig) HasRepoId() bool {
	if o != nil && !isNil(o.RepoId) {
		return true
	}

	return false
}

// SetRepoId gets a reference to the given string and assigns it to the RepoId field.
func (o *ObjectWorkspaceConfig) SetRepoId(v string) {
	o.RepoId = &v
}

// GetRevHash returns the RevHash field value if set, zero value otherwise.
func (o *ObjectWorkspaceConfig) GetRevHash() string {
	if o == nil || isNil(o.RevHash) {
		var ret string
		return ret
	}
	return *o.RevHash
}

// GetRevHashOk returns a tuple with the RevHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectWorkspaceConfig) GetRevHashOk() (*string, bool) {
	if o == nil || isNil(o.RevHash) {
		return nil, false
	}
	return o.RevHash, true
}

// HasRevHash returns a boolean if a field has been set.
func (o *ObjectWorkspaceConfig) HasRevHash() bool {
	if o != nil && !isNil(o.RevHash) {
		return true
	}

	return false
}

// SetRevHash gets a reference to the given string and assigns it to the RevHash field.
func (o *ObjectWorkspaceConfig) SetRevHash(v string) {
	o.RevHash = &v
}

func (o ObjectWorkspaceConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.RepoId) {
		toSerialize["repoId"] = o.RepoId
	}
	if !isNil(o.RevHash) {
		toSerialize["revHash"] = o.RevHash
	}
	return json.Marshal(toSerialize)
}

type NullableObjectWorkspaceConfig struct {
	value *ObjectWorkspaceConfig
	isSet bool
}

func (v NullableObjectWorkspaceConfig) Get() *ObjectWorkspaceConfig {
	return v.value
}

func (v *NullableObjectWorkspaceConfig) Set(val *ObjectWorkspaceConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectWorkspaceConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectWorkspaceConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectWorkspaceConfig(val *ObjectWorkspaceConfig) *NullableObjectWorkspaceConfig {
	return &NullableObjectWorkspaceConfig{value: val, isSet: true}
}

func (v NullableObjectWorkspaceConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectWorkspaceConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
