/*
openapi for sibyl2 server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Sibyl2ClazzWithPath struct for Sibyl2ClazzWithPath
type Sibyl2ClazzWithPath struct {
	// which contains language-specific contents
	Extras   map[string]interface{} `json:"extras,omitempty"`
	Language *string                `json:"language,omitempty"`
	Module   *string                `json:"module,omitempty"`
	Name     *string                `json:"name,omitempty"`
	Path     *string                `json:"path,omitempty"`
	Span     *CoreSpan              `json:"span,omitempty"`
}

// NewSibyl2ClazzWithPath instantiates a new Sibyl2ClazzWithPath object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSibyl2ClazzWithPath() *Sibyl2ClazzWithPath {
	this := Sibyl2ClazzWithPath{}
	return &this
}

// NewSibyl2ClazzWithPathWithDefaults instantiates a new Sibyl2ClazzWithPath object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSibyl2ClazzWithPathWithDefaults() *Sibyl2ClazzWithPath {
	this := Sibyl2ClazzWithPath{}
	return &this
}

// GetExtras returns the Extras field value if set, zero value otherwise.
func (o *Sibyl2ClazzWithPath) GetExtras() map[string]interface{} {
	if o == nil || isNil(o.Extras) {
		var ret map[string]interface{}
		return ret
	}
	return o.Extras
}

// GetExtrasOk returns a tuple with the Extras field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2ClazzWithPath) GetExtrasOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Extras) {
		return map[string]interface{}{}, false
	}
	return o.Extras, true
}

// HasExtras returns a boolean if a field has been set.
func (o *Sibyl2ClazzWithPath) HasExtras() bool {
	if o != nil && !isNil(o.Extras) {
		return true
	}

	return false
}

// SetExtras gets a reference to the given map[string]interface{} and assigns it to the Extras field.
func (o *Sibyl2ClazzWithPath) SetExtras(v map[string]interface{}) {
	o.Extras = v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *Sibyl2ClazzWithPath) GetLanguage() string {
	if o == nil || isNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2ClazzWithPath) GetLanguageOk() (*string, bool) {
	if o == nil || isNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *Sibyl2ClazzWithPath) HasLanguage() bool {
	if o != nil && !isNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *Sibyl2ClazzWithPath) SetLanguage(v string) {
	o.Language = &v
}

// GetModule returns the Module field value if set, zero value otherwise.
func (o *Sibyl2ClazzWithPath) GetModule() string {
	if o == nil || isNil(o.Module) {
		var ret string
		return ret
	}
	return *o.Module
}

// GetModuleOk returns a tuple with the Module field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2ClazzWithPath) GetModuleOk() (*string, bool) {
	if o == nil || isNil(o.Module) {
		return nil, false
	}
	return o.Module, true
}

// HasModule returns a boolean if a field has been set.
func (o *Sibyl2ClazzWithPath) HasModule() bool {
	if o != nil && !isNil(o.Module) {
		return true
	}

	return false
}

// SetModule gets a reference to the given string and assigns it to the Module field.
func (o *Sibyl2ClazzWithPath) SetModule(v string) {
	o.Module = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Sibyl2ClazzWithPath) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2ClazzWithPath) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Sibyl2ClazzWithPath) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Sibyl2ClazzWithPath) SetName(v string) {
	o.Name = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *Sibyl2ClazzWithPath) GetPath() string {
	if o == nil || isNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2ClazzWithPath) GetPathOk() (*string, bool) {
	if o == nil || isNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *Sibyl2ClazzWithPath) HasPath() bool {
	if o != nil && !isNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *Sibyl2ClazzWithPath) SetPath(v string) {
	o.Path = &v
}

// GetSpan returns the Span field value if set, zero value otherwise.
func (o *Sibyl2ClazzWithPath) GetSpan() CoreSpan {
	if o == nil || isNil(o.Span) {
		var ret CoreSpan
		return ret
	}
	return *o.Span
}

// GetSpanOk returns a tuple with the Span field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2ClazzWithPath) GetSpanOk() (*CoreSpan, bool) {
	if o == nil || isNil(o.Span) {
		return nil, false
	}
	return o.Span, true
}

// HasSpan returns a boolean if a field has been set.
func (o *Sibyl2ClazzWithPath) HasSpan() bool {
	if o != nil && !isNil(o.Span) {
		return true
	}

	return false
}

// SetSpan gets a reference to the given CoreSpan and assigns it to the Span field.
func (o *Sibyl2ClazzWithPath) SetSpan(v CoreSpan) {
	o.Span = &v
}

func (o Sibyl2ClazzWithPath) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Extras) {
		toSerialize["extras"] = o.Extras
	}
	if !isNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if !isNil(o.Module) {
		toSerialize["module"] = o.Module
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !isNil(o.Span) {
		toSerialize["span"] = o.Span
	}
	return json.Marshal(toSerialize)
}

type NullableSibyl2ClazzWithPath struct {
	value *Sibyl2ClazzWithPath
	isSet bool
}

func (v NullableSibyl2ClazzWithPath) Get() *Sibyl2ClazzWithPath {
	return v.value
}

func (v *NullableSibyl2ClazzWithPath) Set(val *Sibyl2ClazzWithPath) {
	v.value = val
	v.isSet = true
}

func (v NullableSibyl2ClazzWithPath) IsSet() bool {
	return v.isSet
}

func (v *NullableSibyl2ClazzWithPath) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSibyl2ClazzWithPath(val *Sibyl2ClazzWithPath) *NullableSibyl2ClazzWithPath {
	return &NullableSibyl2ClazzWithPath{value: val, isSet: true}
}

func (v NullableSibyl2ClazzWithPath) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSibyl2ClazzWithPath) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
