/*
openapi for sibyl2 server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Sibyl2FunctionContextSlim struct for Sibyl2FunctionContextSlim
type Sibyl2FunctionContextSlim struct {
	BodySpan *CoreSpan `json:"bodySpan,omitempty"`
	Calls    []string  `json:"calls,omitempty"`
	// which contains language-specific contents
	Extras map[string]interface{} `json:"extras,omitempty"`
	// language
	Lang         *string           `json:"lang,omitempty"`
	Name         *string           `json:"name,omitempty"`
	Parameters   []ObjectValueUnit `json:"parameters,omitempty"`
	Path         *string           `json:"path,omitempty"`
	Receiver     *string           `json:"receiver,omitempty"`
	Returns      []ObjectValueUnit `json:"returns,omitempty"`
	ReverseCalls []string          `json:"reverseCalls,omitempty"`
	Span         *CoreSpan         `json:"span,omitempty"`
}

// NewSibyl2FunctionContextSlim instantiates a new Sibyl2FunctionContextSlim object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSibyl2FunctionContextSlim() *Sibyl2FunctionContextSlim {
	this := Sibyl2FunctionContextSlim{}
	return &this
}

// NewSibyl2FunctionContextSlimWithDefaults instantiates a new Sibyl2FunctionContextSlim object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSibyl2FunctionContextSlimWithDefaults() *Sibyl2FunctionContextSlim {
	this := Sibyl2FunctionContextSlim{}
	return &this
}

// GetBodySpan returns the BodySpan field value if set, zero value otherwise.
func (o *Sibyl2FunctionContextSlim) GetBodySpan() CoreSpan {
	if o == nil || isNil(o.BodySpan) {
		var ret CoreSpan
		return ret
	}
	return *o.BodySpan
}

// GetBodySpanOk returns a tuple with the BodySpan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2FunctionContextSlim) GetBodySpanOk() (*CoreSpan, bool) {
	if o == nil || isNil(o.BodySpan) {
		return nil, false
	}
	return o.BodySpan, true
}

// HasBodySpan returns a boolean if a field has been set.
func (o *Sibyl2FunctionContextSlim) HasBodySpan() bool {
	if o != nil && !isNil(o.BodySpan) {
		return true
	}

	return false
}

// SetBodySpan gets a reference to the given CoreSpan and assigns it to the BodySpan field.
func (o *Sibyl2FunctionContextSlim) SetBodySpan(v CoreSpan) {
	o.BodySpan = &v
}

// GetCalls returns the Calls field value if set, zero value otherwise.
func (o *Sibyl2FunctionContextSlim) GetCalls() []string {
	if o == nil || isNil(o.Calls) {
		var ret []string
		return ret
	}
	return o.Calls
}

// GetCallsOk returns a tuple with the Calls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2FunctionContextSlim) GetCallsOk() ([]string, bool) {
	if o == nil || isNil(o.Calls) {
		return nil, false
	}
	return o.Calls, true
}

// HasCalls returns a boolean if a field has been set.
func (o *Sibyl2FunctionContextSlim) HasCalls() bool {
	if o != nil && !isNil(o.Calls) {
		return true
	}

	return false
}

// SetCalls gets a reference to the given []string and assigns it to the Calls field.
func (o *Sibyl2FunctionContextSlim) SetCalls(v []string) {
	o.Calls = v
}

// GetExtras returns the Extras field value if set, zero value otherwise.
func (o *Sibyl2FunctionContextSlim) GetExtras() map[string]interface{} {
	if o == nil || isNil(o.Extras) {
		var ret map[string]interface{}
		return ret
	}
	return o.Extras
}

// GetExtrasOk returns a tuple with the Extras field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2FunctionContextSlim) GetExtrasOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Extras) {
		return map[string]interface{}{}, false
	}
	return o.Extras, true
}

// HasExtras returns a boolean if a field has been set.
func (o *Sibyl2FunctionContextSlim) HasExtras() bool {
	if o != nil && !isNil(o.Extras) {
		return true
	}

	return false
}

// SetExtras gets a reference to the given map[string]interface{} and assigns it to the Extras field.
func (o *Sibyl2FunctionContextSlim) SetExtras(v map[string]interface{}) {
	o.Extras = v
}

// GetLang returns the Lang field value if set, zero value otherwise.
func (o *Sibyl2FunctionContextSlim) GetLang() string {
	if o == nil || isNil(o.Lang) {
		var ret string
		return ret
	}
	return *o.Lang
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2FunctionContextSlim) GetLangOk() (*string, bool) {
	if o == nil || isNil(o.Lang) {
		return nil, false
	}
	return o.Lang, true
}

// HasLang returns a boolean if a field has been set.
func (o *Sibyl2FunctionContextSlim) HasLang() bool {
	if o != nil && !isNil(o.Lang) {
		return true
	}

	return false
}

// SetLang gets a reference to the given string and assigns it to the Lang field.
func (o *Sibyl2FunctionContextSlim) SetLang(v string) {
	o.Lang = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Sibyl2FunctionContextSlim) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2FunctionContextSlim) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Sibyl2FunctionContextSlim) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Sibyl2FunctionContextSlim) SetName(v string) {
	o.Name = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *Sibyl2FunctionContextSlim) GetParameters() []ObjectValueUnit {
	if o == nil || isNil(o.Parameters) {
		var ret []ObjectValueUnit
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2FunctionContextSlim) GetParametersOk() ([]ObjectValueUnit, bool) {
	if o == nil || isNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *Sibyl2FunctionContextSlim) HasParameters() bool {
	if o != nil && !isNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given []ObjectValueUnit and assigns it to the Parameters field.
func (o *Sibyl2FunctionContextSlim) SetParameters(v []ObjectValueUnit) {
	o.Parameters = v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *Sibyl2FunctionContextSlim) GetPath() string {
	if o == nil || isNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2FunctionContextSlim) GetPathOk() (*string, bool) {
	if o == nil || isNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *Sibyl2FunctionContextSlim) HasPath() bool {
	if o != nil && !isNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *Sibyl2FunctionContextSlim) SetPath(v string) {
	o.Path = &v
}

// GetReceiver returns the Receiver field value if set, zero value otherwise.
func (o *Sibyl2FunctionContextSlim) GetReceiver() string {
	if o == nil || isNil(o.Receiver) {
		var ret string
		return ret
	}
	return *o.Receiver
}

// GetReceiverOk returns a tuple with the Receiver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2FunctionContextSlim) GetReceiverOk() (*string, bool) {
	if o == nil || isNil(o.Receiver) {
		return nil, false
	}
	return o.Receiver, true
}

// HasReceiver returns a boolean if a field has been set.
func (o *Sibyl2FunctionContextSlim) HasReceiver() bool {
	if o != nil && !isNil(o.Receiver) {
		return true
	}

	return false
}

// SetReceiver gets a reference to the given string and assigns it to the Receiver field.
func (o *Sibyl2FunctionContextSlim) SetReceiver(v string) {
	o.Receiver = &v
}

// GetReturns returns the Returns field value if set, zero value otherwise.
func (o *Sibyl2FunctionContextSlim) GetReturns() []ObjectValueUnit {
	if o == nil || isNil(o.Returns) {
		var ret []ObjectValueUnit
		return ret
	}
	return o.Returns
}

// GetReturnsOk returns a tuple with the Returns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2FunctionContextSlim) GetReturnsOk() ([]ObjectValueUnit, bool) {
	if o == nil || isNil(o.Returns) {
		return nil, false
	}
	return o.Returns, true
}

// HasReturns returns a boolean if a field has been set.
func (o *Sibyl2FunctionContextSlim) HasReturns() bool {
	if o != nil && !isNil(o.Returns) {
		return true
	}

	return false
}

// SetReturns gets a reference to the given []ObjectValueUnit and assigns it to the Returns field.
func (o *Sibyl2FunctionContextSlim) SetReturns(v []ObjectValueUnit) {
	o.Returns = v
}

// GetReverseCalls returns the ReverseCalls field value if set, zero value otherwise.
func (o *Sibyl2FunctionContextSlim) GetReverseCalls() []string {
	if o == nil || isNil(o.ReverseCalls) {
		var ret []string
		return ret
	}
	return o.ReverseCalls
}

// GetReverseCallsOk returns a tuple with the ReverseCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2FunctionContextSlim) GetReverseCallsOk() ([]string, bool) {
	if o == nil || isNil(o.ReverseCalls) {
		return nil, false
	}
	return o.ReverseCalls, true
}

// HasReverseCalls returns a boolean if a field has been set.
func (o *Sibyl2FunctionContextSlim) HasReverseCalls() bool {
	if o != nil && !isNil(o.ReverseCalls) {
		return true
	}

	return false
}

// SetReverseCalls gets a reference to the given []string and assigns it to the ReverseCalls field.
func (o *Sibyl2FunctionContextSlim) SetReverseCalls(v []string) {
	o.ReverseCalls = v
}

// GetSpan returns the Span field value if set, zero value otherwise.
func (o *Sibyl2FunctionContextSlim) GetSpan() CoreSpan {
	if o == nil || isNil(o.Span) {
		var ret CoreSpan
		return ret
	}
	return *o.Span
}

// GetSpanOk returns a tuple with the Span field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sibyl2FunctionContextSlim) GetSpanOk() (*CoreSpan, bool) {
	if o == nil || isNil(o.Span) {
		return nil, false
	}
	return o.Span, true
}

// HasSpan returns a boolean if a field has been set.
func (o *Sibyl2FunctionContextSlim) HasSpan() bool {
	if o != nil && !isNil(o.Span) {
		return true
	}

	return false
}

// SetSpan gets a reference to the given CoreSpan and assigns it to the Span field.
func (o *Sibyl2FunctionContextSlim) SetSpan(v CoreSpan) {
	o.Span = &v
}

func (o Sibyl2FunctionContextSlim) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.BodySpan) {
		toSerialize["bodySpan"] = o.BodySpan
	}
	if !isNil(o.Calls) {
		toSerialize["calls"] = o.Calls
	}
	if !isNil(o.Extras) {
		toSerialize["extras"] = o.Extras
	}
	if !isNil(o.Lang) {
		toSerialize["lang"] = o.Lang
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !isNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !isNil(o.Receiver) {
		toSerialize["receiver"] = o.Receiver
	}
	if !isNil(o.Returns) {
		toSerialize["returns"] = o.Returns
	}
	if !isNil(o.ReverseCalls) {
		toSerialize["reverseCalls"] = o.ReverseCalls
	}
	if !isNil(o.Span) {
		toSerialize["span"] = o.Span
	}
	return json.Marshal(toSerialize)
}

type NullableSibyl2FunctionContextSlim struct {
	value *Sibyl2FunctionContextSlim
	isSet bool
}

func (v NullableSibyl2FunctionContextSlim) Get() *Sibyl2FunctionContextSlim {
	return v.value
}

func (v *NullableSibyl2FunctionContextSlim) Set(val *Sibyl2FunctionContextSlim) {
	v.value = val
	v.isSet = true
}

func (v NullableSibyl2FunctionContextSlim) IsSet() bool {
	return v.isSet
}

func (v *NullableSibyl2FunctionContextSlim) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSibyl2FunctionContextSlim(val *Sibyl2FunctionContextSlim) *NullableSibyl2FunctionContextSlim {
	return &NullableSibyl2FunctionContextSlim{value: val, isSet: true}
}

func (v NullableSibyl2FunctionContextSlim) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSibyl2FunctionContextSlim) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
