/*
openapi for sibyl2 server

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ExtractorValueUnit struct for ExtractorValueUnit
type ExtractorValueUnit struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewExtractorValueUnit instantiates a new ExtractorValueUnit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExtractorValueUnit() *ExtractorValueUnit {
	this := ExtractorValueUnit{}
	return &this
}

// NewExtractorValueUnitWithDefaults instantiates a new ExtractorValueUnit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExtractorValueUnitWithDefaults() *ExtractorValueUnit {
	this := ExtractorValueUnit{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ExtractorValueUnit) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExtractorValueUnit) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ExtractorValueUnit) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ExtractorValueUnit) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ExtractorValueUnit) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExtractorValueUnit) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
    return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ExtractorValueUnit) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ExtractorValueUnit) SetType(v string) {
	o.Type = &v
}

func (o ExtractorValueUnit) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableExtractorValueUnit struct {
	value *ExtractorValueUnit
	isSet bool
}

func (v NullableExtractorValueUnit) Get() *ExtractorValueUnit {
	return v.value
}

func (v *NullableExtractorValueUnit) Set(val *ExtractorValueUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableExtractorValueUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableExtractorValueUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtractorValueUnit(val *ExtractorValueUnit) *NullableExtractorValueUnit {
	return &NullableExtractorValueUnit{value: val, isSet: true}
}

func (v NullableExtractorValueUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtractorValueUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


